---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2892384912-xw9rMOZXg8aAPhRy4zUM586u991f98ZoxEAzjR0
:access_token_secret: HSnPa7uTtNQAJ8Icm3oGPmajymrHeDZvzfztkXZO6CS3u
