// Excercise 4-2 From Begining C
// Make a multipication table of size generated by the user.
#include <stdio.h>

int main(void)
{
	unsigned int table = 0;
	unsigned int i = 0;
	unsigned int j = 0;
	
	printf("This is a program to make a multipication table."
										" How large do you want it?\n");
	printf("\nWhole numbers only please!");
	scanf("  %d", &table);
	
	printf("Here you go!\n");
	for(i = 1; i - 1 < table; ++i)
	{
		printf("\n");
		for(j = 1; j - 1 < table ; ++j)
		{
			printf("%d  ", i * j);
		}
	}

	printf("\n");
	return 0;
}
